### ISSUE TITLE
IP Protection: Will there be an option for users to turn off the IP Protection?

### ISSUE THREAD

**Issue by suryakantchoudhary** [GoogleChrome/ip-protection#16]
If so, will this option be available for all users or just enterprise?

**Comment by AtebMT** [comment]
This would be really helpful. Is it possible for users to provide a safe-list of hosts that can see their IP address but still hide IP address from hosts not in the safe list?

**Comment by ps959** [comment]
Any more updates on enterprise controls over this setting?

**Comment by DavidSchinazi** [comment]
There will be enterprise controls to disable IP Protection. Sorry for not responding sooner, we added this to the explainer in fe1741dce2fa99aedb855cdf4d0b0c8379390dee but forgot to update this issue. Since the explainer now contains the sentence "It will be possible for users and enterprise-managed versions of Chrome to disable IP Protection.", I think we can close this issue as completed.
